-- proxquery — structured match corpus (single source of truth, part 2)
-- =====================================================================
-- The `(doc, query) -> expected` recheck cases, as typed tuples rather than the
-- opaque exprs in proxquery_cases.sql. Keeping doc and query split lets the SAME
-- data drive three things:
--   * the portable function check `ts_prox_match(to_tsvector('simple',doc), query)`
--     on BOTH implementations (proxquery_diff_test.sql / proxquery_pure_test.sql),
--   * the extension-only operator/index test, which builds one indexed temp table
--     from the distinct docs and runs `tsv @~@ query` (proxquery_operator_test.sql).
-- `expected` is the `::text` of the recheck (true/false). Error and literal-
-- tsvector cases stay in proxquery_cases.sql (they aren't `to_tsvector(doc)` pairs).
-- doc/query are dollar-quoted so quotes, backslashes and `|` need no escaping.

DROP TABLE IF EXISTS _prox_match;
CREATE TEMP TABLE _prox_match(label text, doc text, query text, expected text);

INSERT INTO _prox_match(label, doc, query, expected) VALUES
  ('c1',  $d$the quick brown fox jumps$d$,           $q$"quick brown" <~3> jumps$q$,            $x$true$x$),
  ('c2',  $d$the quick brown fox jumps$d$,           $q$"quick brown" <~1> jumps$q$,            $x$false$x$),
  ('c3',  $d$alpha beta x gamma delta$d$,            $q$"alpha beta" <~3> "gamma delta"$q$,     $x$true$x$),
  ('c4',  $d$quick brown z z z z z z email$d$,       $q$"quick brown" <!~3> email$q$,           $x$true$x$),
  ('c5',  $d$quick brown email$d$,                   $q$"quick brown" <!~3> email$q$,           $x$false$x$),
  ('c6',  $d$the apple pie$d$,                        $q$"appl* pie"$q$,                         $x$true$x$),
  ('c7',  $d$the orange pie$d$,                       $q$"appl* pie"$q$,                         $x$false$x$),
  ('c8',  $d$the biology class$d$,                    $q$"*ology class"$q$,                      $x$true$x$),
  ('c9',  $d$the geography class$d$,                  $q$"*ology class"$q$,                      $x$false$x$),
  ('c10', $d$the best test class$d$,                  $q$"te?t class"$q$,                        $x$true$x$),
  ('c11', $d$the best tense class$d$,                 $q$"te?t class"$q$,                        $x$false$x$),
  ('c12', $d$the biology class$d$,                    $q$*ology <-> class$q$,                    $x$true$x$),
  ('g1',  $d$this text is confidential$d$,            $q$*ial$q$,                                $x$true$x$),
  ('g2',  $d$this text is confidential$d$,            $q$con*ial$q$,                             $x$true$x$),
  ('g3',  $d$this text is public$d$,                  $q$con*ial$q$,                             $x$false$x$),
  ('g4',  $d$pick the best test$d$,                   $q$te?t$q$,                                $x$true$x$),
  ('g5',  $d$pick the best tense$d$,                  $q$te?t$q$,                                $x$false$x$),
  ('g6',  $d$we love c sharp$d$,                      $q$'c'$q$,                                 $x$true$x$),
  ('g7',  $d$we love rust$d$,                         $q$'c'$q$,                                 $x$false$x$),
  ('gr1', $d$a z z z z z z z z z z b c$d$,            $q$(a & b) <~5> c$q$,                      $x$false$x$),
  ('gr2', $d$a z z z z z z z z z z b c$d$,            $q$a & (b <~5> c)$q$,                      $x$true$x$),
  ('gr3', $d$a z z z z z c$d$,                        $q$(a | b) <~5> c$q$,                      $x$false$x$),
  ('gr4', $d$a z z z z z c$d$,                        $q$a | (b <~5> c)$q$,                      $x$true$x$),
  ('gr5', $d$c alone$d$,                              $q$a & b | c$q$,                           $x$true$x$),
  ('gr6', $d$c alone$d$,                              $q$a & (b | c)$q$,                         $x$false$x$),
  ('gr7', $d$a x b$d$,                                $q$a <-5> b$q$,                            $x$true$x$),
  ('gr8', $d$a x b$d$,                                $q$b <-5> a$q$,                            $x$false$x$),
  ('gr9', $d$a b z z z z z z b$d$,                    $q$a <!~5> b$q$,                           $x$false$x$),
  ('gr10',$d$a b z z z z z z b$d$,                    $q$b <!~5> a$q$,                           $x$true$x$),
  ('m1',  $d$a x b$d$,                                $q$a <~2> b$q$,                            $x$true$x$),
  ('m2',  $d$a x y b$d$,                              $q$a <~2> b$q$,                            $x$false$x$),
  ('m3',  $d$a x y b$d$,                              $q$a <~3> b$q$,                            $x$true$x$),
  ('m4',  $d$a x b$d$,                                $q$a <-2> b$q$,                            $x$true$x$),
  ('m5',  $d$b x a$d$,                                $q$a <-2> b$q$,                            $x$false$x$),
  ('m6',  $d$a x b$d$,                                $q$a <2> b$q$,                             $x$true$x$),
  ('m7',  $d$a x y b$d$,                              $q$a <2> b$q$,                             $x$false$x$),
  ('m8',  $d$a b$d$,                                  $q$a <-> b$q$,                             $x$true$x$),
  ('m9',  $d$email confidential foo bar baz qux confidential$d$, $q$confidential <!~5> email$q$, $x$true$x$),
  ('m10', $d$email confidential confidential email$d$,$q$confidential <!~5> email$q$,           $x$false$x$),
  ('m11', $d$price foo discount$d$,                   $q$price <!-5> discount$q$,                $x$false$x$),
  ('m12', $d$discount foo price$d$,                   $q$price <!-5> discount$q$,                $x$true$x$),
  ('m13', $d$discount foo price$d$,                   $q$price <!~5> discount$q$,                $x$false$x$),
  ('m14', $d$a c b$d$,                                $q$(a & b) <~2> c$q$,                      $x$true$x$),
  ('m15', $d$a w w w w c b$d$,                        $q$(a & b) <~2> c$q$,                      $x$false$x$),
  ('m16', $d$alpha x beta x gamma$d$,                 $q$alpha <~2> beta <~2> gamma$q$,          $x$true$x$),
  ('m17', $d$alpha x x x beta x x x gamma$d$,         $q$alpha <~2> beta <~2> gamma$q$,          $x$false$x$),
  ('m18', $d$alpha beta x x x x x x beta gamma$d$,    $q$alpha <~2> beta <~2> gamma$q$,          $x$false$x$),
  ('n1',  $d$a b x c z z z z d$d$,                    $q$("a b" <~5> c) <~10> d$q$,              $x$true$x$),
  ('n2',  $d$a b x c z z z z z z z z z z d$d$,        $q$("a b" <~5> c) <~10> d$q$,              $x$false$x$),
  ('n3',  $d$a b c$d$,                                $q$((a <~5> b) <~10> c) <!~3> d$q$,        $x$true$x$),
  ('o1',  $d$the cat sat$d$,                          $q$(cat | dog) <~2> sat$q$,                $x$true$x$),
  ('o2',  $d$the dog sat$d$,                          $q$(cat | dog) <~2> sat$q$,                $x$true$x$),
  ('o3',  $d$the bird sat$d$,                         $q$(cat | dog) <~2> sat$q$,                $x$false$x$),
  ('o4',  $d$cat z z z z z email$d$,                  $q$(cat | dog) <!~2> email$q$,             $x$true$x$),
  ('r1',  $d$call me at 123456789 today$d$,           $q$##[0-9]{9}##$q$,                        $x$true$x$),
  ('r2',  $d$call me at 12345 today$d$,               $q$##[0-9]{9}##$q$,                        $x$false$x$),
  ('r3',  $d$the colour is nice$d$,                   $q$##colou?r##$q$,                         $x$true$x$),
  ('r4',  $d$the color is nice$d$,                    $q$##colou?r##$q$,                         $x$true$x$),
  ('dist1',$d$a b c$d$,                               $q$a <~2> c$q$,                            $x$true$x$),
  ('dist2',$d$a b c$d$,                               $q$c <~2> a$q$,                            $x$true$x$),
  ('dist3',$d$a b c$d$,                               $q$a <~1> c$q$,                            $x$false$x$),
  ('dist4',$d$a b c$d$,                               $q$c <~1> a$q$,                            $x$false$x$),
  ('shp1', $d$privileged and confidential$d$,         $q$confidential <!~5> "privileged and confidential"$q$, $x$false$x$),
  ('shp2', $d$privileged and confidential w w w w w w w w confidential$d$, $q$confidential <!~5> "privileged and confidential"$q$, $x$true$x$),
  ('shp3', $d$privileged and confidential foo confidential$d$, $q$confidential <!~5> "privileged and confidential"$q$, $x$false$x$),
  ('cs2', $d$the apple pie$d$,                         $q$appl:*$q$,                             $x$true$x$),
  ('cs4', $d$apple pie$d$,                             $q$appl:* <~2> pie$q$,                    $x$true$x$),
  ('cs5', $d$apple$d$,                                 $q$apple*$q$,                             $x$true$x$),
  ('cs6', $d$applesauce$d$,                            $q$apple*$q$,                             $x$true$x$),
  ('cs7', $d$appl$d$,                                  $q$apple*$q$,                             $x$false$x$),
  ('bs1', $d$a b$d$,                                   $q$'a\b'$q$,                              $x$false$x$),
  ('bs2', $d$ab$d$,                                    $q$'a\b'$q$,                              $x$false$x$),
  ('ra1', $d$the colourful flag$d$,                    $q$##colou?r##$q$,                        $x$false$x$),
  ('ra2', $d$the colour is nice$d$,                    $q$##^colou?r$##$q$,                      $x$true$x$),
  ('ra3', $d$the cat sat$d$,                           $q$##cat|dog##$q$,                        $x$true$x$),
  ('ra4', $d$category dogma$d$,                        $q$##cat|dog##$q$,                        $x$false$x$),
  ('ra5', $d$the colour is nice$d$,                    $q$##^colou?r##$q$,                       $x$true$x$),
  ('ra6', $d$the colour is nice$d$,                    $q$##colou?r$##$q$,                       $x$true$x$),
  ('z0a', $d$a b$d$,                                   $q$a <~0> b$q$,                           $x$false$x$),
  ('z0d', $d$a b$d$,                                   $q$a <0> b$q$,                            $x$false$x$),
  ('span1',$d$a 2 b 4 5 c$d$,                          $q$(a <~5> c) <~1> b$q$,                  $x$true$x$),
  ('span2',$d$a 2 b 4 5 c$d$,                          $q$(a <~5> c) <~2> b$q$,                  $x$true$x$),
  ('span3',$d$a x c x x g x x x a x c$d$,              $q$(a <~2> c) <~1> g$q$,                  $x$false$x$),
  ('span4',$d$a x c x x g x x x a x c$d$,              $q$(a <~2> c) <~1> x$q$,                  $x$true$x$),
  ('chstrict',$d$one two three four five six seven orange nine apple eleven banana$d$, $q$apple <~2> banana <~2> orange$q$, $x$true$x$),
  -- non-ASCII: accented Latin and CJK. Locale-INDEPENDENT (no uppercase to case-fold),
  -- so they agree on any CI collation. Two things are deliberately NOT asserted here
  -- because their tokenization is locale-dependent (see docs/CONFIG_AWARE.md):
  -- uppercase-accent case-folding, and emoji (a token under C, dropped under en_US.UTF-8).
  ('u1',  $d$le café est bon$d$,                     $q$café$q$,                                $x$true$x$),
  ('u2',  $d$le café est bon$d$,                     $q$café <~2> bon$q$,                       $x$true$x$),
  ('u3',  $d$le café est bon$d$,                     $q$café <~1> bon$q$,                       $x$false$x$),
  ('u4',  $d$résumé and resume$d$,                   $q$résumé$q$,                              $x$true$x$),
  ('u5',  $d$plain resume here$d$,                   $q$résumé$q$,                              $x$false$x$),
  ('u6',  $d$el niño pequeño$d$,                     $q$niño$q$,                                $x$true$x$),
  ('u7',  $d$el niño pequeño$d$,                     $q$nino$q$,                                $x$false$x$),
  ('u8',  $d$中文 文档 搜索$d$,                        $q$中文$q$,                                 $x$true$x$),
  ('u9',  $d$中文 文档 搜索$d$,                        $q$中文 <~2> 搜索$q$,                       $x$true$x$),
  ('u10', $d$中文 文档 搜索$d$,                        $q$中文 <~1> 搜索$q$,                       $x$false$x$),
  ('u11', $d$日本語$d$,                               $q$日本$q$,                                 $x$false$x$);
